title: WhatTheJunkyard
email: silchenko.whatthetea@gmail.com
author: Oleksii "WhatTheTea" Silchenko
description: >
  Oleksii "WhatTheTea" Silchenko personal blog. C# Developer from Ukraine. <br/>
  #dotnet #csharp #ukraine #winui #asp.net
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WhatTheTea
linkedin_username: WhatTheTea
facebook_username: WhatTh3T3a
telegram_username: WhatTheTea

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
